import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, NavLink, Route, Routes, useParams} from 'react-router-dom';
import {QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient} from '@tanstack/react-query';
import {ArrowRight, BookOpen, CheckCircle2, CircleHelp, ExternalLink, FileText, History, Home, LifeBuoy, RotateCcw, Search, Send, ShieldCheck, Sparkles, ThumbsDown, ThumbsUp, Upload} from 'lucide-react';
import './styles.css';

const API='/api';
type Doc={document_id:string;title:string;document_type:string;service:string;version:string;updated_at:string;chunk_count:number;tags:string[];publisher?:string;source_url?:string;content?:string};
type Source={chunk:{chunk_id:string;document_id:string;title:string;section_title:string;text:string;document_type:string;service:string;version:string;publisher?:string;source_url?:string}};
type Answer={response_id:string;conversation_id:string;answer:string;answer_mode:'AI synthesis'|'Guided fallback';evidence_support:string;evidence_explanation:string;latency_ms:number;citations:{document_id:string}[];sources:Source[]};
async function get<T>(path:string):Promise<T>{const response=await fetch(API+path);if(!response.ok)throw new Error('We could not load this information. Please try again.');return response.json()}

const nav=[['/', 'Overview', Home],['/investigate', 'Investigation Desk', LifeBuoy],['/knowledge', 'Knowledge Library', BookOpen],['/incidents', 'Solved Cases', History]] as const;

function Shell(){return <div className="appShell"><aside className="sidebar"><div className="brand"><div className="brandMark">R</div><div><strong>ResolveAI Support</strong><small>Trusted technical answers</small></div></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="sidebarNote"><ShieldCheck size={17}/><div><b>Verifiable sources</b><span>Every answer links back to real public evidence.</span></div></div></aside><main><Routes><Route path="/" element={<Overview/>}/><Route path="/investigate" element={<Investigation/>}/><Route path="/ask" element={<Investigation/>}/><Route path="/knowledge" element={<Knowledge/>}/><Route path="/documents/:id" element={<DocumentView/>}/><Route path="/incidents" element={<Incidents/>}/></Routes></main></div>}
function PageHeader({kicker,title,subtitle,action}:{kicker?:string;title:string;subtitle:string;action?:React.ReactNode}){return <header className="pageHeader"><div>{kicker&&<span className="kicker">{kicker}</span>}<h1>{title}</h1><p>{subtitle}</p></div>{action}</header>}

function Overview(){const {data:docs=[]}=useQuery({queryKey:['documents'],queryFn:()=>get<Doc[]>('/documents')});const official=docs.filter(d=>d.document_type==='public_reference').length;const community=docs.filter(d=>d.document_type==='community_support').length;const technologies=new Set(docs.map(d=>d.service)).size;const recent=[...docs].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).slice(0,4);return <><PageHeader kicker="Technical support workspace" title="Good afternoon" subtitle="Find a clear answer and trace every recommendation back to its original public source." action={<NavLink className="primaryAction" to="/investigate">Start an investigation <ArrowRight size={17}/></NavLink>}/><section className="welcomePanel"><div><span className="eyebrow">WHEN SOMETHING BREAKS</span><h2>Describe what you see. We’ll help you narrow it down.</h2><p>Ask about payments, checkout, frontend errors, APIs, login, containers, databases, or infrastructure. If the report is too broad, ResolveAI will tell you exactly what evidence to collect next.</p><NavLink to="/investigate" className="textLink">Open Investigation Desk <ArrowRight size={16}/></NavLink></div><div className="sampleQuestion"><CircleHelp size={20}/><span>Try asking</span><blockquote>“PayPal checkout returns an invalid client error after deployment. How do I diagnose it?”</blockquote></div></section><section className="sectionBlock"><div className="sectionHeading"><div><span className="eyebrow">REAL-WORLD KNOWLEDGE</span><h2>Built from traceable public sources</h2></div><NavLink to="/knowledge">Browse all documents</NavLink></div><div className="coverageGrid"><Stat value={community} label="Solved community cases" note="Real Stack Overflow questions with accepted answers"/><Stat value={official} label="Official references" note="Trusted upstream operational documentation"/><Stat value={technologies} label="Support areas" note="Payments, web, APIs, identity, data and infrastructure"/></div></section><section className="sectionBlock"><div className="sectionHeading"><div><span className="eyebrow">RECENTLY UPDATED</span><h2>Latest source material</h2></div></div><div className="recentList">{recent.map(doc=><NavLink to={'/documents/'+doc.document_id} key={doc.document_id}><DocumentIcon type={doc.document_type}/><div><b>{doc.title}</b><span>{friendlyType(doc.document_type)} · {doc.service}</span></div><time>{formatDate(doc.updated_at)}</time><ArrowRight size={16}/></NavLink>)}</div></section></>}
function Stat({value,label,note}:{value:number;label:string;note:string}){return <div className="coverageCard"><strong>{value}</strong><div><b>{label}</b><p>{note}</p></div></div>}

const prompts=["My Stripe checkout fails with a CORS error in the browser console. What should I check?","PayPal checkout returns an invalid client error after deployment. How do I diagnose it?","Users are stuck in an OAuth login redirect loop. What could cause it?","My React page is blank after deployment but the API is healthy. What should I inspect?","A Docker container cannot reach the backend API. How can I debug the connection?","PostgreSQL says password authentication failed for user postgres. What should I check?"];
function Investigation(){
  const [query,setQuery]=useState('');const [conversationId,setConversationId]=useState<string>();const [entries,setEntries]=useState<{question:string;answer:Answer}[]>([]);
  const mutation=useMutation({mutationFn:async(value:string)=>{const history=entries.flatMap(entry=>[{role:'user',content:entry.question},{role:'assistant',content:entry.answer.answer}]);const response=await fetch(API+'/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:value,debug:false,conversation_id:conversationId,history})});if(!response.ok)throw new Error('The investigation could not be completed. Check that the local service is running and try again.');return response.json() as Promise<Answer>},onSuccess:(answer,value)=>{setConversationId(answer.conversation_id);setEntries(previous=>[...previous,{question:value,answer}]);setQuery('')}});
  const run=(value:string)=>{if(value.trim().length>=3)mutation.mutate(value.trim())};const reset=()=>{setEntries([]);setConversationId(undefined);setQuery('');mutation.reset()};
  return <><PageHeader kicker="Guided support" title="Investigation Desk" subtitle="Describe the problem in your own words, then continue the conversation with errors, logs, or results from each check." action={entries.length?<button className="secondaryAction" onClick={reset}><RotateCcw size={15}/> New investigation</button>:undefined}/>
    {entries.length>0&&<section className="conversation">{entries.map((entry,index)=><div className="conversationTurn" key={entry.answer.response_id}><div className="userQuestion"><span>You</span><p>{entry.question}</p></div><Brief data={entry.answer}/>{index===entries.length-1&&<Feedback answer={entry.answer}/>}</div>)}</section>}
    <section className={'investigationBox '+(entries.length?'followUpBox':'')}><div className="inputLabel"><Sparkles size={16}/><span>{entries.length?'What happened after those checks?':'What is happening?'}</span></div><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))run(query)}} placeholder={entries.length?'Add an error message, test result, or ask a follow-up question…':'Describe the symptom, exact error, affected technology, and what changed…'}/><div className="inputFooter"><span>Do not include passwords, tokens, payment details, or personal data.</span><button disabled={mutation.isPending||query.trim().length<3} onClick={()=>run(query)}>{mutation.isPending?'Preparing your answer…':entries.length?'Send follow-up':'Create troubleshooting brief'} <Send size={15}/></button></div></section>
    {!entries.length&&!mutation.isPending&&<section className="promptSection"><span className="eyebrow">EXAMPLES — OR ASK YOUR OWN QUESTION</span><div className="promptGrid">{prompts.map((prompt,index)=><button onClick={()=>run(prompt)} key={prompt}><span>0{index+1}</span><p>{prompt}</p><ArrowRight size={16}/></button>)}</div></section>}
    {mutation.isPending&&<LoadingState/>}{mutation.error&&<div className="message errorMessage"><CircleHelp/><div><b>We couldn’t complete the investigation</b><p>{mutation.error.message}</p></div></div>}</>}
function LoadingState(){return <div className="loadingState"><div className="loadingMark"><Search/></div><div><b>Reviewing the knowledge library</b><p>Checking real solved questions and official references for the closest match.</p></div></div>}

function Brief({data}:{data:Answer}){const uniqueDocs=new Set(data.sources.map(s=>s.chunk.document_id)).size;const insufficient=data.evidence_support==='Insufficient evidence';const general=data.evidence_support==='General diagnostic guidance';return <div className="brief"><div className="briefHeader"><div><span className="eyebrow">{data.answer_mode==='AI synthesis'?'AI TROUBLESHOOTING BRIEF':'TROUBLESHOOTING BRIEF'}</span><h2>{insufficient?'A few details will narrow this down':'Recommended investigation path'}</h2><p>{insufficient?'Start with the checks below, then add the exact error, affected scope, and recent changes for a source-backed diagnosis.':general?'A practical investigation path based on the symptom. It identifies likely causes without pretending that one root cause has already been confirmed.':`Prepared from ${uniqueDocs} relevant source${uniqueDocs===1?'':'s'}. Confirm each step in your own environment before making a production change.`}</p></div><div className={insufficient?'supportState caution':'supportState'}><CheckCircle2 size={18}/><span>{insufficient?'More detail needed':general?'Guided diagnosis':'Sources checked'}</span></div></div><AnswerContent text={data.answer}/>{data.sources.length>0&&<section className="sourceSection"><div className="sectionHeading compact"><div><span className="eyebrow">SOURCE MATERIAL</span><h2>Documents used in this brief</h2></div></div><div className="sourceList">{data.sources.map(source=><NavLink to={'/documents/'+source.chunk.document_id} key={source.chunk.chunk_id}><DocumentIcon type={source.chunk.document_type}/><div><b>{source.chunk.title}</b><span>{source.chunk.section_title} · {friendlyType(source.chunk.document_type)}</span></div>{source.chunk.publisher&&<em>{source.chunk.publisher}</em>}<ArrowRight size={16}/></NavLink>)}</div></section>}</div>}
function Feedback({answer}:{answer:Answer}){const [choice,setChoice]=useState<boolean|null>(null);const [comment,setComment]=useState('');const mutation=useMutation({mutationFn:async(helpful:boolean)=>{const response=await fetch(API+'/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({response_id:answer.response_id,conversation_id:answer.conversation_id,helpful,comment})});if(!response.ok)throw new Error('Feedback could not be saved.')}});if(mutation.isSuccess)return <div className="feedback saved"><CheckCircle2 size={17}/><span>Thank you. Your feedback was saved.</span></div>;return <div className="feedback"><div><b>Was this useful?</b><span>Your feedback helps improve future answers.</span></div><div className="feedbackActions"><button className={choice===true?'active':''} onClick={()=>{setChoice(true);setComment('');mutation.mutate(true)}}><ThumbsUp size={15}/> Yes</button><button className={choice===false?'active':''} onClick={()=>setChoice(false)}><ThumbsDown size={15}/> Not really</button></div>{choice===false&&<div className="feedbackComment"><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="What was missing or incorrect?"/><button disabled={mutation.isPending} onClick={()=>mutation.mutate(false)}>Send feedback</button></div>}</div>}
function RichText({text}:{text:string}){const parts=text.replace(/\*\*/g,'').split(/(\[[A-Z]+(?:-[A-Z0-9.]+)+\])/g);return <>{parts.map((part,index)=>{const match=part.match(/^\[([^\]]+)\]$/);return match?<NavLink className="citation" to={'/documents/'+match[1]} key={index}>{match[1]}</NavLink>:<React.Fragment key={index}>{part}</React.Fragment>})}</>}
function AnswerContent({text}:{text:string}){const blocks=text.split(/(?=^## )/m);return <article className="answerContent">{blocks.map((block,index)=>{const lines=block.trim().split('\n').filter(Boolean);if(!lines.length)return null;const title=lines[0].startsWith('## ')?lines.shift()!.slice(3):'';const featured=title==='Short answer';return <section key={index} className={'answerSection '+(featured?'featured':'')}>{title&&<h3>{title}</h3>}<div>{lines.map((line,i)=>{const cleaned=line.replace(/\*\*/g,'');if(/^\d+\./.test(cleaned))return <div className="actionStep" key={i}><span>{cleaned.match(/^\d+/)?.[0]}</span><p><RichText text={cleaned.replace(/^\d+\.\s*/, '')}/></p></div>;if(cleaned.startsWith('- '))return <div className="checkItem" key={i}><CheckCircle2 size={17}/><p><RichText text={cleaned.slice(2)}/></p></div>;return <p key={i}><RichText text={cleaned}/></p>})}</div></section>})}</article>}

function Knowledge(){const [search,setSearch]=useState('');const [scope,setScope]=useState<'all'|'community'|'official'>('all');const [showUpload,setShowUpload]=useState(false);const {data=[]}=useQuery({queryKey:['documents'],queryFn:()=>get<Doc[]>('/documents')});const rows=useMemo(()=>data.filter(doc=>{const matches=(doc.title+doc.document_id+doc.service+doc.tags.join(' ')).toLowerCase().includes(search.toLowerCase());const scoped=scope==='all'||(scope==='official'&&doc.document_type==='public_reference')||(scope==='community'&&doc.document_type==='community_support');return matches&&scoped}),[data,search,scope]);return <><PageHeader kicker="Traceable knowledge" title="Knowledge Library" subtitle="Add your own manuals and support notes alongside the real public sources already available." action={<button className="primaryAction" onClick={()=>setShowUpload(value=>!value)}><Upload size={16}/> Add a document</button>}/>{showUpload&&<UploadPanel onClose={()=>setShowUpload(false)}/>}<div className="libraryTools"><div className="searchField"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by title, technology, error, or topic"/></div><div className="scopeTabs">{(['all','community','official'] as const).map(value=><button className={scope===value?'active':''} onClick={()=>setScope(value)} key={value}>{value==='all'?'All sources':value==='community'?'Solved community cases':'Official references'}</button>)}</div></div><div className="libraryCount">{rows.length} {rows.length===1?'document':'documents'}</div><div className="documentList">{rows.map(doc=><NavLink to={'/documents/'+doc.document_id} key={doc.document_id}><DocumentIcon type={doc.document_type}/><div className="docMain"><div><b>{doc.title}</b>{doc.document_type==='public_reference'&&<span className="officialBadge">Official</span>}</div><p>{friendlyType(doc.document_type)} · {doc.service}{doc.version&&doc.version!=='community'&&` · ${doc.version}`}</p></div><div className="docMeta"><span>Updated {formatDate(doc.updated_at)}</span><small>{doc.publisher||doc.document_id}</small></div><ArrowRight size={17}/></NavLink>)}</div></>}
function UploadPanel({onClose}:{onClose:()=>void}){const queryClient=useQueryClient();const [file,setFile]=useState<File|null>(null);const [title,setTitle]=useState('');const [service,setService]=useState('');const mutation=useMutation({mutationFn:async()=>{if(!file)throw new Error('Choose a document first.');const form=new FormData();form.append('file',file);form.append('title',title);form.append('service',service||'general');const response=await fetch(API+'/documents/upload',{method:'POST',body:form});const body=await response.json();if(!response.ok)throw new Error(body.detail||'The document could not be added.');return body},onSuccess:()=>queryClient.invalidateQueries({queryKey:['documents']})});return <section className="uploadPanel"><div><span className="eyebrow">ADD ORGANISATIONAL KNOWLEDGE</span><h2>Upload a support document</h2><p>Markdown, text, or text-based PDF · Maximum 5 MB. The document is stored and searched only on this local application.</p></div><div className="uploadFields"><label><span>Document</span><input type="file" accept=".md,.txt,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label><span>Title <small>optional</small></span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Use the file name automatically"/></label><label><span>Topic <small>optional</small></span><input value={service} onChange={e=>setService(e.target.value)} placeholder="e.g. payments or authentication"/></label></div>{mutation.isSuccess?<div className="uploadSuccess"><CheckCircle2 size={17}/><span>Document added and ready to search.</span><button onClick={onClose}>Done</button></div>:<div className="uploadFooter">{mutation.error&&<span className="uploadError">{mutation.error.message}</span>}<button className="secondaryAction" onClick={onClose}>Cancel</button><button className="primaryAction" disabled={!file||mutation.isPending} onClick={()=>mutation.mutate()}>{mutation.isPending?'Adding document…':'Add to library'}</button></div>}</section>}

function DocumentView(){const {id}=useParams();const {data,isLoading}=useQuery({queryKey:['document',id],queryFn:()=>get<Doc>('/documents/'+id)});if(isLoading||!data)return <LoadingState/>;return <><PageHeader kicker={data.document_type==='public_reference'?'Official reference':'Knowledge document'} title={data.title} subtitle={`${friendlyType(data.document_type)} · ${data.service}${data.version?` · ${data.version}`:''}`} action={data.source_url?<a className="secondaryAction" href={data.source_url} target="_blank" rel="noreferrer">View original <ExternalLink size={16}/></a>:undefined}/><article className="documentView">{data.publisher&&<div className="publisherNote"><ShieldCheck size={18}/><div><b>Published by {data.publisher}</b><span>This imported reference remains linked to its original source.</span></div></div>}{data.content?.split('\n').map((line,index)=>{const clean=line.replace(/[*`]/g,'');if(line.startsWith('# '))return <h1 key={index}>{clean.slice(2)}</h1>;if(line.startsWith('## '))return <h2 key={index}>{clean.slice(3)}</h2>;if(line.startsWith('### '))return <h3 key={index}>{clean.slice(4)}</h3>;if(line.startsWith('- '))return <div className="docBullet" key={index}><span/><p>{clean.slice(2)}</p></div>;return clean.trim()?<p key={index}>{clean}</p>:null})}</article></>}

function Incidents(){const [search,setSearch]=useState('');const {data=[]}=useQuery({queryKey:['incidents'],queryFn:()=>get<Doc[]>('/incidents')});const rows=data.filter(doc=>(doc.title+doc.document_id+doc.service+doc.tags.join(' ')).toLowerCase().includes(search.toLowerCase()));return <><PageHeader kicker="Learn from real questions" title="Solved Cases" subtitle="Review public technical questions and the accepted answers that solved them. Open any case to see its original Stack Overflow source."/><div className="searchField standalone"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by technology, error, topic, or question"/></div><div className="incidentList">{rows.map(doc=><NavLink to={'/documents/'+doc.document_id} key={doc.document_id}><div className="incidentDate"><span>{new Date(doc.updated_at).toLocaleDateString('en',{month:'short'})}</span><b>{new Date(doc.updated_at).getDate()}</b><small>{new Date(doc.updated_at).getFullYear()}</small></div><div><span className="incidentId">{doc.document_id}</span><h3>{doc.title}</h3><p>{doc.service} · {doc.publisher||'Public source'}</p></div><div className="incidentStatus"><span>Solved</span><ArrowRight size={17}/></div></NavLink>)}</div></>}

function DocumentIcon({type}:{type:string}){return <div className={'documentIcon '+(type==='public_reference'?'official':'')}>{type==='incident'?<History/>:<FileText/>}</div>}
function friendlyType(type:string){return ({troubleshooting:'Troubleshooting guide',runbook:'Operations runbook',incident:'Incident report',community_support:'Solved community question',support_ticket:'Support case',release_note:'Release notes',api_doc:'API reference',architecture:'Architecture guide',database:'Database guide',known_issue:'Known issue',product_doc:'Product reference',public_reference:'Official technology documentation',uploaded_document:'Uploaded organisational document'} as Record<string,string>)[type]||'Knowledge document'}
function formatDate(value:string){if(!value)return 'Unknown';return new Date(value).toLocaleDateString('en',{day:'numeric',month:'short',year:'numeric'})}

const client=new QueryClient();
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter><Shell/></BrowserRouter></QueryClientProvider></React.StrictMode>);
