"""Generate the deterministic, publish-safe Nexora enterprise corpus from canonical facts."""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; RAW=ROOT/"data"/"raw"; GOLD=ROOT/"data"/"golden"
SERVICES={
"payment-service":{"owner":"Commerce Payments","versions":["4.0","4.1","4.2","4.2.1","4.3"],"deps":["PostgreSQL 16","Kafka","Redis"],"errors":["PAY-201","PAY-307","DB-104","DB-207"]},
"order-service":{"owner":"Order Lifecycle","versions":["3.6","3.7","3.7.2","3.8"],"deps":["PostgreSQL 16","Kafka"],"errors":["ORD-502","ORD-504","KAFKA-301"]},
"authentication-service":{"owner":"Identity Platform","versions":["5.0","5.1","5.1.2"],"deps":["Redis","PostgreSQL 16"],"errors":["AUTH-401","AUTH-429","CACHE-118"]},
"inventory-service":{"owner":"Supply Platform","versions":["2.8","2.9","2.9.1"],"deps":["PostgreSQL 16","Kafka","Redis"],"errors":["INV-409","INV-503","KAFKA-302"]},
"catalog-service":{"owner":"Merchandising","versions":["6.2","6.3"],"deps":["OpenSearch","Redis"],"errors":["CAT-404","SEARCH-206"]},
"cart-service":{"owner":"Checkout Experience","versions":["3.2","3.3"],"deps":["Redis","Kafka"],"errors":["CART-409","CACHE-119"]},
"notification-service":{"owner":"Customer Messaging","versions":["2.1","2.2"],"deps":["Kafka"],"errors":["NOTIFY-429","KAFKA-305"]},
"api-gateway":{"owner":"Edge Platform","versions":["7.0","7.1"],"deps":["Nginx","Redis"],"errors":["GW-429","GW-502"]},
"search-service":{"owner":"Discovery Platform","versions":["4.4","4.5"],"deps":["OpenSearch","Kafka"],"errors":["SEARCH-429","SEARCH-503"]},
"customer-service":{"owner":"Customer Domain","versions":["2.4","2.5"],"deps":["PostgreSQL 16","Kafka"],"errors":["CUS-409","DB-211"]},}
ERRORS={}
for service,facts in SERVICES.items():
    for code in facts["errors"]:
        ERRORS[code]={"service":service,"severity":"SEV-2" if code in {"DB-104","ORD-502","AUTH-401","INV-503"} else "SEV-3","description":f"{service} rejected or could not complete an operation because a required dependency or invariant failed.","diagnostics":["correlate the request ID across gateway and service logs","compare active configuration with the version baseline","inspect dependency saturation and retry rates"],"remediation":"Stabilize the dependency, restore the documented configuration baseline, and verify with a canary request before clearing the alert."}
ERRORS["DB-104"].update(description="Database connection acquisition timed out before a checkout transaction could begin.",remediation="For Payment Service 4.2 on PostgreSQL 16 set checkout pool maximumSize to 24, minimumIdle to 6, connectionTimeoutMs to 3000, then deploy 4.2.1, which restores version-aware pool sizing.")
ERRORS["PAY-307"].update(description="Payment authorization result remained indeterminate after the upstream processor deadline.",remediation="Query the provider by idempotency key; never blindly repeat authorization. Fixed retry classification ships in 4.3.")
INCIDENTS=[
{"id":"INC-2025-003","title":"Redis eviction caused authentication refresh failures","service":"authentication-service","date":"2025-02-03","version":"5.0","error":"CACHE-118","cause":"a volatile-lru policy evicted refresh-token state during a campaign traffic spike","fix":"reserved memory and changed the token cache to noeviction"},
{"id":"INC-2025-007","title":"Order events accumulated after consumer rebalance storm","service":"order-service","date":"2025-03-14","version":"3.7","error":"KAFKA-301","cause":"a Kubernetes rollout restarted every consumer in the group inside one session timeout","fix":"set maxUnavailable to one and introduced a termination drain hook"},
{"id":"INC-2025-011","title":"Inventory reservations conflicted during replay","service":"inventory-service","date":"2025-04-22","version":"2.9","error":"INV-409","cause":"replayed reservation messages used a non-stable operation key","fix":"deployed 2.9.1 with deterministic reservation idempotency keys"},
{"id":"INC-2025-018","title":"Checkout failures after Payment Service 4.2 rollout","service":"payment-service","date":"2025-06-18","version":"4.2","error":"DB-104","cause":"4.2 applied a fixed pool maximum of 40 per pod; with PostgreSQL 16 and 12 replicas this exhausted the 300-session database budget","fix":"reduced maximumSize to 24 and minimumIdle to 6, then deployed 4.2.1"},
{"id":"INC-2025-024","title":"Payment authorization ambiguity during processor latency","service":"payment-service","date":"2025-08-09","version":"4.2.1","error":"PAY-307","cause":"the provider response crossed the client deadline after authorization committed","fix":"reconciled by idempotency key and disabled unsafe automatic retry"},
{"id":"INC-2025-031","title":"Catalog search returned stale prices","service":"catalog-service","date":"2025-10-02","version":"6.3","error":"SEARCH-206","cause":"an OpenSearch alias switch completed before the price enrichment consumer caught up","fix":"gated alias promotion on consumer watermark"},
{"id":"INC-2025-037","title":"Gateway throttled trusted batch clients","service":"api-gateway","date":"2025-11-19","version":"7.1","error":"GW-429","cause":"client identity normalization dropped the tenant partition from rate-limit keys","fix":"restored tenant-aware keys and replayed rejected batches"},
{"id":"INC-2026-002","title":"Order confirmation delayed by Kafka lag","service":"order-service","date":"2026-01-12","version":"3.7.2","error":"KAFKA-301","cause":"a schema-registry timeout triggered repeated consumer restarts rather than the earlier rollout rebalance pattern","fix":"pinned the cached schema and raised registry circuit-breaker tolerance"},
{"id":"INC-2026-006","title":"Notification provider backpressure","service":"notification-service","date":"2026-02-21","version":"2.2","error":"NOTIFY-429","cause":"provider quotas were shared across transactional and campaign traffic","fix":"split quota pools and prioritized transactional topics"},
{"id":"INC-2026-010","title":"Customer merge deadlocks","service":"customer-service","date":"2026-03-17","version":"2.5","error":"DB-211","cause":"two merge workers locked customer identities in opposite order","fix":"ordered locks by canonical customer ID and serialized duplicate merge keys"},]
TICKETS=[
{"id":"SUP-1842","customer":"Aster Retail","service":"payment-service","version":"4.2","error":"DB-104","wording":"payment backend started choking right after the 4.1 to 4.2 update on Postgres 16","incident":"INC-2025-018"},
{"id":"SUP-1861","customer":"BlueYonder Market","service":"payment-service","version":"4.2","error":"DB-104","wording":"checkout keeps timing out after latest update even though payment pods look green","incident":"INC-2025-018"},
{"id":"SUP-1904","customer":"Northstar Goods","service":"order-service","version":"3.7","error":"KAFKA-301","wording":"orders finish but confirmations take twenty minutes","incident":"INC-2025-007"},
{"id":"SUP-1933","customer":"Cobalt Home","service":"authentication-service","version":"5.0","error":"CACHE-118","wording":"users are randomly signed out during traffic bursts","incident":"INC-2025-003"},
{"id":"SUP-1970","customer":"Mosaic Wholesale","service":"inventory-service","version":"2.9","error":"INV-409","wording":"reserved stock is duplicated when messages are replayed","incident":"INC-2025-011"},
{"id":"SUP-2018","customer":"Evergreen Shop","service":"payment-service","version":"4.2.1","error":"PAY-307","wording":"bank approved a payment but our UI says it timed out","incident":"INC-2025-024"},
{"id":"SUP-2077","customer":"Halo Sports","service":"catalog-service","version":"6.3","error":"SEARCH-206","wording":"search results show yesterday's price for a few minutes","incident":"INC-2025-031"},
{"id":"SUP-2112","customer":"Juno Office","service":"api-gateway","version":"7.1","error":"GW-429","wording":"nightly import got rate limited after gateway upgrade","incident":"INC-2025-037"},
{"id":"SUP-2166","customer":"Kite Outfitters","service":"order-service","version":"3.7.2","error":"KAFKA-301","wording":"orders pile up whenever schema registry has a wobble","incident":"INC-2026-002"},
{"id":"SUP-2210","customer":"Lumen Direct","service":"notification-service","version":"2.2","error":"NOTIFY-429","wording":"receipts wait behind marketing mail","incident":"INC-2026-006"},]
KNOWN_ISSUES=[
{"id":"KI-PAY-042","title":"Payment 4.2 pool oversubscription on PostgreSQL 16","service":"payment-service","version":"4.2","error":"DB-104","status":"fixed in 4.2.1"},
{"id":"KI-ORD-037","title":"Order consumer restart loop during schema-registry latency","service":"order-service","version":"3.7.2","error":"KAFKA-301","status":"mitigated by cached schema fallback"},]

def front(doc_id,title,kind,service,version="",updated="2026-03-20",tags=None,severity=""):
    return f'''---\ndocument_id: {doc_id}\ntitle: {title}\ndocument_type: {kind}\nservice: {service}\nversion: {version}\nproduct: nexora-commerce\ncreated_at: 2025-01-10\nupdated_at: {updated}\nenvironment: [staging, production]\ntags: [{", ".join(tags or [service,kind])}]\nseverity: {severity}\n---\n\n'''
def operational_sections(service,version,error,focus):
    deps=", ".join(SERVICES[service]["deps"]); fact=ERRORS[error]
    paragraphs=[]
    for phase in ["Triage","Diagnosis","Containment","Recovery","Verification","Prevention"]:
        paragraphs.append(f'''## {phase}\n\nThe {phase.lower()} objective for {service} {version} is to preserve customer safety while collecting enough evidence to distinguish application health from dependency health. {focus} Operators correlate gateway request IDs with {service} traces and review {deps} saturation. A green Kubernetes readiness probe proves only that the process accepts traffic; it does not prove that downstream capacity is available.\n\nFor {error}, the catalog definition is: {fact['description']} The team checks service error rate, p95 latency, active and waiting connections, Kafka lag where applicable, and the deployment timeline. Evidence is recorded before changing configuration. Commands are executed through approved observability and deployment tooling; secrets and customer payloads must never be pasted into tickets.\n\nDecision criteria are explicit. If the error began within thirty minutes of a version or configuration rollout, compare the live manifest with the release baseline. If dependency saturation is shared by several services, escalate to the platform owner. If only one tenant is affected, examine tenant routing and rate limits. The documented remediation is: {fact['remediation']} A canary must complete ten representative operations before broad restoration.\n\nRollback remains available until verification passes. Restore the previous immutable deployment revision, keep database migrations that are backward compatible, and stop if a downgrade would read data written in a newer incompatible format. Close the phase only after dashboards remain within the service-level objective for fifteen minutes and a synthetic checkout traverses API Gateway, Authentication, Cart, Inventory, Payment, Order, and Notification.''')
    return "\n\n".join(paragraphs)
def write_doc(folder,name,text):
    path=RAW/folder/name; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding="utf-8")

def generate():
    for p in [RAW,GOLD,ROOT/"data"/"evaluation"]: p.mkdir(parents=True,exist_ok=True)
    for filename,data in [("services.json",SERVICES),("error_codes.json",ERRORS),("incidents.json",INCIDENTS),("support_tickets.json",TICKETS),("known_issues.json",KNOWN_ISSUES),("versions.json",{s:v["versions"] for s,v in SERVICES.items()}),("relationships.json",{"checkout_flow":["api-gateway","authentication-service","cart-service","inventory-service","payment-service","order-service","notification-service"],"event_bus":"Kafka","primary_database":"PostgreSQL 16"})]: (GOLD/filename).write_text(json.dumps(data,indent=2),encoding="utf-8")
    catalog=front("DOC-ERR-001","Nexora Error Code Catalog","product_doc","platform",updated="2026-03-20",tags=["errors","reference"])+"# Nexora Error Code Catalog\n\n"
    for code,f in ERRORS.items(): catalog+=f"## {code}: {f['description']}\n\n**Service:** {f['service']}  \n**Severity:** {f['severity']}\n\n### Symptoms and causes\n\n{f['description']} The code is emitted with a request ID and dependency state so operators can distinguish transient saturation from a persistent configuration mismatch.\n\n### Diagnostic steps\n\n"+"\n".join(f"{i+1}. {x.capitalize()}." for i,x in enumerate(f['diagnostics']))+f"\n\n### Remediation\n\n{f['remediation']}\n\n"
    write_doc("product_docs","error-code-catalog.md",catalog)
    arch=front("ARCH-001","Nexora Commerce Platform Architecture","architecture","platform",updated="2026-03-10",tags=["architecture","checkout"])+"# Nexora Commerce Platform Architecture\n\n"+operational_sections("payment-service","4.2.1","PAY-201","The synchronous checkout path is API Gateway → Authentication → Cart → Inventory → Payment → Order; Notification consumes the resulting event asynchronously.")
    write_doc("architecture","platform-architecture.md",arch)
    for idx,(service,facts) in enumerate(SERVICES.items(),1):
        code=facts["errors"][0]; version=facts["versions"][-1]; title=f"{service.replace('-',' ').title()} Operations and Troubleshooting Guide"
        body=front(f"DOC-{service.split('-')[0].upper()}-{idx:03d}",title,"troubleshooting",service,version,tags=[service,"troubleshooting",code])+f"# {title}\n\n## Scope\n\nThis guide is the current operating reference owned by {facts['owner']}. It covers versions {', '.join(facts['versions'])} and dependencies {', '.join(facts['deps'])}.\n\n"+operational_sections(service,version,code,f"The guide treats {code} as the primary worked example while cross-checking {', '.join(facts['errors'])}.")
        write_doc("troubleshooting",f"{service}-guide.md",body)
    runbooks=[("RUN-PAY-001","Payment Service Production Runbook","payment-service","4.2.1","DB-104"),("RUN-DB-001","PostgreSQL Failover Runbook","payment-service","4.2.1","DB-207"),("RUN-KAFKA-001","Kafka Consumer Lag Runbook","order-service","3.7.2","KAFKA-301"),("RUN-REDIS-001","Redis Cache Recovery Runbook","authentication-service","5.1.2","CACHE-118"),("RUN-AUTH-001","Authentication Recovery Runbook","authentication-service","5.1.2","AUTH-401"),("RUN-DEP-001","Deployment Rollback Runbook","payment-service","4.2.1","PAY-201")]
    for did,title,service,version,error in runbooks:
        body=front(did,title,"runbook",service,version,tags=["runbook",service,error])+f"# {title}\n\n## Purpose and prerequisites\n\nThis runbook provides a controlled production procedure. The incident commander, service owner, and communications lead must be identified before mutations begin. Confirm dashboard access, an approved change record, the last known-good revision, and a rollback checkpoint.\n\n"+operational_sections(service,version,error,"Every command requires a named operator and a peer verifier. Do not improvise database or payment changes from memory.")
        write_doc("runbooks",title.lower().replace(" ","-")+".md",body)
    for inc in INCIDENTS:
        log=f"{inc['date']}T14:32:11Z {inc['service']} ERROR {inc['error']} request_id=req-7f21 dependency_state=degraded waiting=127"
        body=front(inc["id"],inc["title"],"incident",inc["service"],inc["version"],inc["date"],tags=["incident",inc["error"]],severity="SEV-2")+f'''# {inc['id']}: {inc['title']}\n\n## Summary and impact\n\nA production degradation affected {inc['service']} {inc['version']}. Customers experienced delayed or failed operations and support observed {inc['error']}. The incident was contained without data loss.\n\n## Timeline\n\n- 14:27 alert crossed the error-budget threshold.\n- 14:32 on-call correlated {inc['error']} with the deployment and dependency dashboards.\n- 14:48 the team reproduced the failure in a production-like canary.\n- 15:06 containment reduced customer impact.\n- 15:41 the permanent corrective change completed verification.\n\n## Detection and logs\n\n```text\n{log}\n```\n\n## Investigation and root cause\n\nThe team eliminated gateway, authentication, and tenant-specific hypotheses by tracing complete requests. The confirmed root cause was {inc['cause']}. Similar symptoms can have different causes; in particular, INC-2025-007 and INC-2026-002 both involve Kafka lag but require different corrective actions.\n\n## Resolution and recovery\n\nThe responders {inc['fix']}. They replayed only idempotent work, compared business counters before and after recovery, and kept the incident open until fifteen minutes of stable service-level indicators.\n\n## Contributing factors\n\nThe pre-production load profile underrepresented production concurrency. Alert context showed the symptom but not the recently changed configuration. The change review also lacked a dependency-capacity calculation.\n\n## Preventive actions\n\nThe owning team added a version-aware configuration test, a deployment canary, and a dashboard joining service replicas to dependency capacity. Future releases must record the calculation in release evidence.\n\n## Related records\n\nError code {inc['error']}; service guide for {inc['service']}; corresponding customer support tickets and current release notes.\n\n'''+operational_sections(inc["service"],inc["version"],inc["error"],"This appendix preserves the validated response pattern learned during the incident.")
        write_doc("incidents",inc["id"].lower()+".md",body)
    for ticket in TICKETS:
        inc=next(x for x in INCIDENTS if x["id"]==ticket["incident"])
        body=front(ticket["id"],f"{ticket['customer']} — {ticket['error']} support case","support_ticket",ticket["service"],ticket["version"],inc["date"],tags=["support",ticket["error"]])+f'''# {ticket['id']}: {ticket['customer']}\n\n## Customer report\n\nPriority P2. The customer wrote: “{ticket['wording']}.” Their production environment used {ticket['service']} {ticket['version']} on Kubernetes with the standard Nexora dependency profile.\n\n## Troubleshooting conversation\n\nSupport first confirmed scope, start time, affected tenants, and the exact upgrade window. The engineer requested request IDs and configuration values rather than secrets or full payloads. Healthy pods did not rule out downstream saturation. The engineer searched exact identifier {ticket['error']} and then broadened the query using the customer's informal description.\n\n## Diagnosis\n\nThe evidence matched {ticket['incident']}: {inc['cause']}. Metrics and a controlled canary excluded unrelated gateway and authentication failures.\n\n## Resolution\n\nSupport guided the customer through the approved containment and the permanent fix: {inc['fix']}. The customer verified representative operations, business counters, and fifteen minutes of normal error and latency levels.\n\n## Related documentation\n\n{ticket['incident']}; {ticket['error']} in DOC-ERR-001; current {ticket['service']} troubleshooting guide and release notes.\n\n'''+operational_sections(ticket["service"],ticket["version"],ticket["error"],"The following internal notes explain why each support step was safe and how escalation decisions were made.")
        write_doc("support_tickets",ticket["id"].lower()+".md",body)
    releases=[("REL-PAY-4.1","Payment Service 4.1 Release Notes","4.1","Stable adaptive connection-pool sizing; no PostgreSQL 16 fixed-pool behavior."),("REL-PAY-4.2","Payment Service 4.2 Release Notes","4.2","Introduced a fixed default maximumSize of 40 per pod. Known issue: DB-104 on PostgreSQL 16 when aggregate pod capacity exceeds the database session budget. Temporary workaround is maximumSize 24 and minimumIdle 6."),("REL-PAY-4.2.1","Payment Service 4.2.1 Release Notes","4.2.1","Permanently fixes DB-104 by restoring version-aware pool sizing. Recommended PostgreSQL 16 baseline: maximumSize 24, minimumIdle 6, connectionTimeoutMs 3000."),("REL-PAY-4.3","Payment Service 4.3 Release Notes","4.3","Adds safe PAY-307 reconciliation by idempotency key and deprecates blind authorization retry."),("REL-ORD-3.7.2","Order Service 3.7.2 Release Notes","3.7.2","Adds consumer drain hooks and cached schema fallback for KAFKA-301 scenarios.")]
    for did,title,version,change in releases:
        body=front(did,title,"release_note","payment-service" if "PAY" in did else "order-service",version,updated="2026-01-20",tags=["release",version])+f"# {title}\n\n## Changes\n\n{change}\n\n## Upgrade requirements\n\nReview capacity, preserve backward-compatible migrations, canary one pod, and compare the active manifest with the documented baseline. Older release notes describe the state at publication time; later patch notes supersede workarounds when explicitly stated.\n\n"+operational_sections("payment-service" if "PAY" in did else "order-service",version,"DB-104" if "PAY" in did else "KAFKA-301","This release appendix records validation and rollback expectations.")
        write_doc("release_notes",did.lower()+".md",body)
    api_specs=[("API-PAY-001","Payment API","payment-service","POST /api/v1/payments/authorize","PAY-307"),("API-ORD-001","Order API","order-service","POST /api/v1/orders","ORD-502"),("API-INV-001","Inventory API","inventory-service","POST /api/v1/reservations","INV-409"),("API-AUTH-001","Authentication API","authentication-service","POST /api/v1/auth/token","AUTH-429")]
    for did,title,service,endpoint,error in api_specs:
        body=front(did,title,"api_doc",service,SERVICES[service]["versions"][-1],tags=["api",service,error])+f'''# {title}\n\n## {endpoint}\n\nRequires a bearer token and an `Idempotency-Key` for state-changing operations. Tenant and request identifiers are propagated to every downstream call. Rate-limit responses include a bounded `Retry-After`; clients must use exponential backoff with jitter.\n\n```json\n{{"tenantId":"tenant-demo","amount":12500,"currency":"EUR","reference":"order-4815"}}\n```\n\nA successful response contains the resource ID, state, version, and correlation ID. Error responses use `{{"code":"{error}","message":"safe summary","requestId":"req-7f21"}}`. Never use the human-readable message for program logic.\n\n## Version behavior\n\nCurrent clients must preserve idempotency keys across uncertain outcomes. Version negotiation uses the URL major version and additive response fields. Breaking schema changes require a new major endpoint.\n\n'''+operational_sections(service,SERVICES[service]["versions"][-1],error,"API troubleshooting begins with the request ID, authentication state, rate-limit headers, and idempotency key.")
        write_doc("api_docs",did.lower()+".md",body)
    db=front("DB-MIG-016","PostgreSQL 16 Migration and Pool Sizing Guide","database","payment-service","4.2.1",tags=["postgresql","migration","DB-104"])+"# PostgreSQL 16 Migration and Pool Sizing Guide\n\n## Capacity formula\n\nReserve 20 percent of PostgreSQL sessions for administration and migrations. Divide the remaining service budget by the maximum production replica count, not the current count. For Payment Service 4.2.1 the approved baseline is maximumSize 24, minimumIdle 6, connectionTimeoutMs 3000. Payment Service 4.2 used 40 per pod and can trigger DB-104 with twelve replicas against a 300-session budget.\n\n"+operational_sections("payment-service","4.2.1","DB-104","Migration rehearsals must use PostgreSQL 16 and production-equivalent replica counts.")
    write_doc("database","postgresql-16-migration.md",db)
    for issue in KNOWN_ISSUES:
        body=front(issue["id"],issue["title"],"known_issue",issue["service"],issue["version"],tags=["known-issue",issue["error"]])+f"# {issue['title']}\n\n## Status\n\n{issue['status']}. This notice supersedes informal workarounds that conflict with the current release note. Operators must match both service version and dependency conditions before applying it.\n\n"+operational_sections(issue["service"],issue["version"],issue["error"],"Known-issue guidance is intentionally narrow; similar symptoms still require evidence-based diagnosis.")
        write_doc("known_issues",issue["id"].lower()+".md",body)
    questions=[]; base=[("What caused DB-104 after upgrading Payment Service to version 4.2 on PostgreSQL 16?",["INC-2025-018","REL-PAY-4.2.1","DB-MIG-016"],"incident_resolution"),("Which incident was associated with DB-104?",["INC-2025-018"],"exact_identifier"),("How was DB-104 permanently fixed?",["REL-PAY-4.2.1","INC-2025-018"],"version_sensitive"),("Have we had previous Kafka consumer lag incidents affecting Order Service?",["INC-2025-007","INC-2026-002"],"multi_document"),("What does PAY-307 mean and which versions are affected?",["DOC-ERR-001","REL-PAY-4.3","INC-2025-024"],"exact_identifier"),("What is the recommended pool configuration for Payment Service 4.2.1?",["DB-MIG-016","REL-PAY-4.2.1"],"version_sensitive"),("What quantum-computing provider does Nexora use?",[],"unanswerable")]
    for i in range(50):
        q,docs,cat=base[i%len(base)]; questions.append({"id":f"eval-{i+1:03d}","question":q if i<len(base) else q+f" (scenario {i//len(base)+1})","expected_document_ids":docs,"expected_answer_summary":"Retrieve the cited canonical records and avoid unsupported claims.","category":cat,"difficulty":"hard" if cat in {"multi_document","unanswerable"} else "medium"})
    (ROOT/"data"/"evaluation"/"questions.json").write_text(json.dumps(questions,indent=2),encoding="utf-8")
    files=list(RAW.rglob("*.md")); words=sum(len(p.read_text(encoding="utf-8").split()) for p in files)
    print(json.dumps({"documents":len(files),"words":words,"golden_files":7,"evaluation_questions":len(questions)},indent=2))
if __name__=="__main__": generate()
